version: '3.8'

services:
  app:
    container_name: room-booker-backend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ../room-booker:/app
      - ./logs:/app/logs