version: '3.8'

services:
  app:
    container_name: room-booker-backend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: room-booker-db
    environment:
      POSTGRES_USER: roombooker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roombookerdb
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: